### ISSUE TITLE
Gitlab 8.0 not working on wheezy (golang to old)

### ISSUE THREAD

**Issue by Gomez** [debops/ansible-gitlab#29]
Got this error:
```
go build -ldflags "-X main.Version 0.2.10-20150928.143221" -o gitlab-git-http-server
# _/var/local/gitlab/gitlab-git-http-server
./githandler.go:113: undefined: strings.TrimSuffix
./githandler.go:257: undefined: strings.TrimPrefix
```
Fix:
apt-get -t wheezy-backports install golang

This needs to go into docs.

**Comment by Gomez** [comment]
@drybjed Please help me here, how can this dep. added to the role or to the inventory? Is there a example, somewhere?

**Comment by drybjed** [comment]
@Gomez You can check the APT preference for `golang` package. On my Wheezy host, right now it's:
```
golang:
  Installed: (none)
  Candidate: 2:1.0.2-1.1
  Version table:
     2:1.3.3-1~bpo70+1 0
        100 http://ftp.pl.debian.org/debian/ wheezy-backports/main amd64 Packages
     2:1.0.2-1.1 0
        500 http://ftp.pl.debian.org/debian/ wheezy/main amd64 Packages
```
To make that work on Wheezy I would add a `debops.apt_preferences` dependency to `debops.gitlab` so that package from `wheezy-backports` is preferred on Wheezy. Although maybe it's time to start looking into upgrade to Jessie? Have you considered that approach?

**Comment by scibi** [comment]
Hmmm... there are some other issues with Wheezy:

    SyntaxError: /var/local/git/gitlab/vendor/bundle/ruby/1.9.1/gems/doorkeeper-2.1.4/lib/doorkeeper/engine.rb:4: unknown type of %string
      app.config.filter_parameters += %i(client_secret code token)

Do we really want to support it?

**Comment by drybjed** [comment]
The Ruby issue is easily solvable by backporting the Ruby 2.1 packages from Jessie. `debops.backporter` role was supposed to handle that but I've heard that it doesn't work anymore due to the drifting package versions.

I would say that it's time to not actively try and support Debian Wheezy. Do not discourage its use, try and check if a role works on Wheezy, and if it can, make sure that it does via APT preferences, for example. But if there are issues, writing a Jessie-only role should be fine, ie. lack of Wheezy support shouldn't disqualify a role.

In this specific example, I would say we should try and fix backporting Jessie packages via `debops.backporter` to make Ruby work.

**Comment by Gomez** [comment]
I am fine with jessie-only. 
For me the Ruby backport on wheezy worked (months ago) and now the golang backport works too. Got a runnig gitlab 8.0.2 on wheezy, but with the next upgrade i switch to jessie.

This ticket can be closed.
